name: Connect4
version: 0.1.0.0
github: 'Kugge/Haskell-Connect4'
license: GNU3
author: 'Sofiane DJERBI (@Kugge)'
maintainer: 'sofiane.djerbi38@gmail.com'
copyright: '2021 Sofiane DJERBI'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Kugge/Haskell-Connect4#readme>

dependencies:
  - base >= 4.7 && < 5
  - gloss

library:
  source-dirs: src

executables:
  Connect4-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Connect4
